### ISSUE TITLE
Add line Break to segment

### ISSUE THREAD

**Issue by sherwanikhans** [RobHolme/vscode-hl7tools#10]
Hi,
with the new update to VS code, Add line break to segment got broken. It is adding word 'auto' on applying the feature. I have removed and reinstalled the extension which didn't solve the issue.

**Comment by RobHolme** [comment]
Just thought of a quick fix that should get around the issue. I've published an update - this should fix the issue when you get the v1.9.4 update to the extension.

**Comment by sherwanikhans** [comment]
thank Rob, I have been working with 1.26V to go around the problem. I updated the VS code to latest version and got the fix for v1.9.4. it working back again!! Believe me this extension is my life saver on big message analysis.

**Comment by sherwanikhans** [comment]
just check the 'extract matching segment' feature, when the new window opens up it is also adding the 'auto' after every line.

**Comment by RobHolme** [comment]
It impacted quite a few commands. I've added a quick fix for most and released a new version (v1.9.5). The Highlight fields command is still impacted, this will take a bit more work to fix. If I have time on the weekend I'll look at fixing any outstanding issues.

**Comment by RobHolme** [comment]
Updated version (v1.9.6) should now fix all issues relating to the change to the end of line configuration in vscode v1.29. I've noticed the 'Split HL7 Batch Files' command isn't working correctly either, but looks like a separate issue - I'll take a look at this when I have time.

**Comment by sherwanikhans** [comment]
Hey Rob,

The issue is fixed with the new update.

happy holidays!
