### ISSUE TITLE
FEATURE: Remote Selectable List

### ISSUE THREAD

**Issue by revren** [RobHolme/vscode-hl7tools#13]
It would be great if settings.json could contain a lit of HL7 remotes. When executing the HL7 send command the user could select from the list rather than having one default only.

**Comment by RobHolme** [comment]
Thanks for the suggestion - when I get some spare time I'll take a look at adding this.

**Comment by revren** [comment]
Thank you Rob. Ive had a little dig around to see if I could help on that front but have little experience with JS and Extensions. Ill keep trying.

**Comment by RobHolme** [comment]
I've played around with a few ideas tonight. I can populate a list of "favourite" remote endpoints from settings.json into a picklist, with the option of manually entering an endpoint if needed. If no favourites are defined in settings.json, then the current behaviour will apply.

e.g. 

![2019-06-26 20_34_37- Extension Development Host  - test hl7 - Visual Studio Code](https://user-images.githubusercontent.com/23287323/60180319-58703680-9852-11e9-9d48-0433b9835866.png)
 
Would this be suitable?

**Comment by revren** [comment]
Wow! Yes that would work perfectly. Thank you so much

**Comment by RobHolme** [comment]
New version just published.  The settings.json entries to define the favourites is a slightly complicated,  I've copied a sample below. It's basically an array of objects, with each object requiring a Description, Hostname and Port property. Hostname property can be IP address or hostname. VScode seems to require the property labels to be case sensitive.  

```
"hl7tools.FavouriteRemoteHosts": [  
		{  
			"Description": "Dev server",  
			"Hostname": "localhost",
			"Port": 5000
		},
		{
			"Description": "test server",
			"Hostname": "127.0.0.1",
			"Port": 5001
		},
		{
			"Description": "Demo",
			"Hostname": "10.10.10.10",
			"Port": 6000
		}
	],
```

**Comment by revren** [comment]
This works perfectly, thank you very much. Has saved me alot of time
