### ISSUE TITLE
Porting to jetbrains products?

### ISSUE THREAD

**Issue by jasonmacer** [RobHolme/vscode-hl7tools#15]
Hey Rob,

Have you thought about porting this plugin so that it is compatible with JetBrain's products like WebStorm and PHPStorm?

**Comment by RobHolme** [comment]
Hi Jason,

I have no plans (or spare time) to port this to other environments. These aren't products I use personally, so to be honest I don't have the motivation to support anything other than vscode at this stage.

Rob.

**Comment by jasonmacer** [comment]
Okie Dokie! Thanks for the response!
