### ISSUE TITLE
Special characters not displayed properly in messages sent with "HL7 Tools: Send Message" 

### ISSUE THREAD

**Issue by kdtt87** [RobHolme/vscode-hl7tools#16]
When working with a message containing special characters (specifically danish letters ÆØÅ) they are displayed properly in VSCODE.
When the message is sent to a remote system (used HL7 Soup for test), the characters are not displayed properly.
I have verified that the remote system is not the problem, by sending the same message from another source. In this case the characters are displayed properly.

**Comment by RobHolme** [comment]
I've implemented a change that provides a user preference to define the socket encoding used when sending/receiving messages. It looks like HL7 Soup wasn't accepting the default "UTF-8" encoding option used in prior versions of this extension. My testing with HL7 Soup seems to work using "ISO 8859-1" encoding.  

I'm having issues publishing the updated version of the extension at the moment, so might be a few days before I have time to look into the publishing issues. I'll update the issue with details once the new version has been published.

**Comment by RobHolme** [comment]
New version published. To change the encoding when sending/receiving messages, go to File --> Preferences --> Extensions --> HL7 Tools.   Select "ISO-8859-1" from the list of encoding options. 

ISO-8859-1 works for me when tested using 'HL7 Soup' and 'SmartHL7 Receiver' to receive messages with Danish letters. Let me know how your testing goes.

![2020-01-10 14_18_20- Extension Development Host  - Settings - Visual Studio Code](https://user-images.githubusercontent.com/23287323/72130543-cf1aee80-33b4-11ea-858e-486e44a2c87e.png)

**Comment by kdtt87** [comment]
Hi Rob,

I can indeed confirm that it is working now. Both for receiving and sending.

Great work!
