### ISSUE TITLE
Send message command doesn't work for not parsed messages

### ISSUE THREAD

**Issue by lechuckcaptain** [RobHolme/vscode-hl7tools#2]
If the send message is called on a context of message that cannot be properly parsed, the editor returns that the command cannot be found. 

It should be nice if the command would be available also for not HL7 parsed messages, or at least the error message to be more clear.

**Comment by RobHolme** [comment]
I'm having trouble reproducing the issue - the command works for me when sending a plain text (non HL7 file).  The send command doesn't attempt to validate the message, it will send the current document regardless of the content.

The 'command not found error' is usually returned when the command encounters an error/exception. Do you have a sample file that you can  share with me that triggers the issue?  Could you also let me know what platform your are running (Windows, Linux, Mac).

**Comment by lechuckcaptain** [comment]
I'm running VS code on Windows 10. More details about the version in the screenshot below:

![image](https://user-images.githubusercontent.com/341895/29353488-97773de2-826a-11e7-839f-795684aa6da9.png)

With the attached test file, I get the following error:

[test.txt](https://github.com/RobHolme/vscode-hl7tools/files/1227446/test.txt)

Also with simple plain text files I get the error:

![image](https://user-images.githubusercontent.com/341895/29353547-dfb1b510-826a-11e7-9e8a-52018c6c24f5.png)

**Comment by RobHolme** [comment]
Thanks for your help - I think I've identified the issue. Publishing updated version (v1.6.2) that should fix the problem. Let me know if it resolves the issue.

**Comment by lechuckcaptain** [comment]
Fixed! Thanks!
