### ISSUE TITLE
Support custom segments and fields

### ISSUE THREAD

**Issue by nlsdg** [RobHolme/vscode-hl7tools#20]
At the moment there are no descriptions and metadata for segments/fields not in the HL7 specification (Z-segments).
It would be a nice if you could specify a custom schema.js and fields.js with the definitions of segments and fields, which would be merged with the schema selected by way of the message header.

That way you could document your Z-segments, without having to edit the schema files in the extension (and having them overwritten with an update).

**Comment by RobHolme** [comment]
I've published a new version that includes support for a custom segment schema. Set the 'CustomSegmentSchema'  preference to reference the file containing the custom segment schema (full path and file name). e.g.

`"hl7tools.CustomSegmentSchema": c:\schemas\CustomSchema.js`

This file should only contain custom segments - these will be added to the standard segment schemas. The custom schema file must follow the same format as the default segment schemas included with this extension. Each field definition must have values for "datatype", "desc", and "opt" properties. I have assumed only standard datatypes will be used in custom segment. 

Give it a test and let me know how it goes

Example file:

```
var segments = {
    "ZXX": {
        "desc": "Patient Alert Information",
        "fields": [
            {
                "datatype": "SI",
                "desc": "Set ID",
                "opt": 2
            },
            {
                "datatype": "ID",
                "desc": "Alert Action Code",
                "opt": 2
            },
            {
                "datatype": "ST",
                "desc": "Alert Action Reason",
                "opt": 1
            }
    	]
   },
   "ZAA": {
        "desc": "Some other segment description",
        "fields": [
            {
                "datatype": "CWE",
                "desc": "Test Code",
                "opt": 1
            },
            {
                "datatype": "TX",
                "desc": "Test Description",
                "opt": 1
            }
         ]
     }
};

module.exports = segments;
```

**Comment by nlsdg** [comment]
It works! At first it looked like Display Segment Fields and Check required Fields didn't work, but after saving the custom schema and restarting VSCode (twice) that started working as well.
Thank you for the super quick response.
