### ISSUE TITLE
FHS, BHS fields display index off by 1

### ISSUE THREAD

**Issue by jibaro009** [RobHolme/vscode-hl7tools#21]
The fields in the FHS and BHS are off by 1. For example, the encoding characters in both segments are displayed as FHS-1 (Field Separator).

![image](https://user-images.githubusercontent.com/13224853/95217808-9c761900-07c1-11eb-92c8-3feae6183ecf.png)

**Comment by RobHolme** [comment]
Good spot - thanks for finding this. This issue crops up in a few places, I'll publish an updated version one I find some time to test the changes.

**Comment by RobHolme** [comment]
New version of the extension (v1.13.1) released should fix this.
