### ISSUE TITLE
HL7 v2.5.1, MSH-22/23

### ISSUE THREAD

**Issue by wahmedswl** [RobHolme/vscode-hl7tools#23]
Hi, thanks for this awesome extension. It seems like details for MSH-22 & MSH-23 is missing. Its showing it as undefined.

![image](https://user-images.githubusercontent.com/15020561/101544303-42632100-39c7-11eb-8113-9742d1da1114.png)

![image](https://user-images.githubusercontent.com/15020561/101544180-134caf80-39c7-11eb-9c70-8753d60c8636.png)

![image](https://user-images.githubusercontent.com/15020561/101544419-7dfdeb00-39c7-11eb-9282-5eaaf2b6186f.png)

Thanks

**Comment by RobHolme** [comment]
Hi.  MSH-22 and MSH-23 are not defined in HL7 v2.5.1. They are only included in HL7 v2.6+

The v2.5.1 spec only goes as far has MSH-21.

![image](https://user-images.githubusercontent.com/23287323/101587099-63a32c00-3a1e-11eb-8454-6cc344477b57.png)

The schema included with this extension should be aligned with the specification published by HL7 International (https://www.hl7.org/implement/standards/product_section.cfm?section=13). 

Rob.

**Comment by wahmedswl** [comment]
Yes, it should be. But, i am checking in NYSIIS Immunization Guide and it states v2.5.1 and goes on till MSH-22/23.

![image](https://user-images.githubusercontent.com/15020561/101617192-26e13000-3a32-11eb-9462-00ba27759283.png)

Thanks

**Comment by RobHolme** [comment]
Yeah - vendor specifications often stray from the formal specifications. Looks like they have rolled some HL7 v2.6 fields into their spec.
