### ISSUE TITLE
Send Message: Message indicated sent but never received

### ISSUE THREAD

**Issue by Bachomp** [RobHolme/vscode-hl7tools#24]
I am having an issue where when invoking the **Send Message** routine the output is indicating a connection has been establish and the message has been sent however it is never received by the Integration Engine *(IE)*. 

```
[12:10:26 PM] Connected to 10.64.31.75:2000
[12:10:26 PM] Message sent (TEST-REFI12.HL7)
[12:10:56 PM] Connection to 10.64.31.75:2000 has timed out waiting for a response.
[12:10:56 PM] Connection to 10.64.31.75:2000 has been closed
```

The *(IE)* (Lyniate Rhapsody) also confirms the connection and that it has received no message.

If i take that same message and inject it into the *IE* using a windows based Message Testing tool it works. I do however have to change the EOL char of the message to CR. (LR and CRLR do not work)

```
MacOS Version: 10.15.7
HL7 Tools Version: 1.13.1

VS Code Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by RobHolme** [comment]
My best guess is that the Rhapsody endpoint isn't recognising the end of message delimiters (or the extension is failing to send the delimiters correctly). The message is sent using MLLP framing, can confirm that the Rhapsody endpoint configured to use MLLP framing?

The extension should convert either the LR or CRLF EOL characters to use CR as the segment terminator when sending the message, so also possible this could cause issues if it is failing to convert the EOL characters correctly. Works when I test under Windows - however I don't have a MacOS PC to test on. Do you experience the same issue using VSCode on Windows sending to Rhapsody?

**Comment by Bachomp** [comment]
Rhapsody by default receives using the MLLP framework. I've double checked the configuration and can confirm it is correct.

If Rhapsody receives a message that it can't process it sends it to the error queue.

I've tested it on a windows instance of VSC within the same network subnet as the Rhapsody server and it successfully receives an ACK. I tested it on a local windows instance and it too failed.

Let me check with our security team to ensure it isn't stomping on the traffic.

**Comment by Bachomp** [comment]
Are we able to specify the local port used? 
Looking like it might be a VPN firewall issue. Looking into it further.

**Comment by RobHolme** [comment]
No way to specify a static source port that I know of, this is managed by the OS. Never seen this supported in any app and would be highly problematic if even possible. From memory I believe you can constrain the range used for dynamic ports at the OS level - but I would strongly advise against changing this. Making the pool too small would break network connectivity for all apps. In any case firewall rules will typically be based on the destination port.

Given it works from a local subnet it seems to confirm you suspicion that there is some form of network inspection or firewall restricting the traffic.  Although the logging you copied into your original post seems to confirm a successful connection to 10.64.31.75 on port 2000 (I think the timeout reported is waiting for an ACK after the message is sent). This kind of contradicts the theory that the connection is blocked.

Some integration engines allow you to define connection restrictions on the interfaces - maybe take a look to see is this has been constrained to only accept messages from the local subnet?

**Comment by Bachomp** [comment]
Rhapsody Integration Engine has the ability to specify the local port  per TCP connection point. With that said, it seems the issue was related to the VPN firewalling. I've since moved VPNs after a network infra refresh and it is working as expected over the VPN. 

Thanks for your time and apologies for the bum steer
