### ISSUE TITLE
In the ACK message the CR (0x0D) after the MSA segment is missing

### ISSUE THREAD

**Issue by msi22** [RobHolme/vscode-hl7tools#27]
When the plugin is used for receiving HL7 messages the message can be received but the generated HL7 ACK message is not HL7 compliant. The CR (0x0D) after the MSA segment (last segment) is missing.

Information from the HL7 standard: http://www.hl7.eu/HL7v2x/v28/std28/ch02.html#Heading35
* chapter "2.6 MESSAGE CONSTRUCTION RULES"
* CR is a terminator and not a separator and the pseudo code shows, that it is inserted after each segment

**Comment by RobHolme** [comment]
Thanks for spotting this. 

An updated version (v2.0.1) of the extension has been published that fixes this issue.

**Comment by msi22** [comment]
Thank you for the quick fix. Now it works.
