### ISSUE TITLE
Is it possible to save a modified or received HL7 message with CR (0x0D) as segment terminator?

### ISSUE THREAD

**Issue by msi22** [RobHolme/vscode-hl7tools#28]
When an HL7 message gets modified or is received the HL7 message gets corrupted during save because the segments get not terminated with CR (0x0D) anymore and have normal line breaks. Is it possible to save the HL7 messages in an HL7 compliant way?

Information from the HL7 standard: http://www.hl7.eu/HL7v2x/v28/std28/ch02.html#Heading25

**Comment by RobHolme** [comment]
This is a limitation of Visual Studio Code. It only support CRLF or LF line termination.

ref: https://github.com/Microsoft/vscode/issues/35797
