### ISSUE TITLE
Support built-in Format Document command

### ISSUE THREAD

**Issue by hamdawg** [RobHolme/vscode-hl7tools#29]
Please make the `Add Linebreak to Segments` command happen with the `Format Document` Command

According to VS Code documentation, it is [best-practice](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices) to support the Format Document command.

**Comment by RobHolme** [comment]
The document formatter has been added. Same behaviour as ```Add Linebreak to Segments```, only with the addition of removing occurrences of multiple line breaks as well (i.e. blank lines between segments are removed). v2.0.4 of the extension has been published with these changes.
