### ISSUE TITLE
Add segment from IHE-PAM FR

### ISSUE THREAD

**Issue by FFManiac** [RobHolme/vscode-hl7tools#34]
Can you implement segments added by IHE-PAM FR ?
 For exemple ZBE / ZFD…

thank you

I add link to PDF from interopsante.org

[pdf](https://www.interopsante.org/offres/doc_inline_src/412/Publication-IHE_FRANCE_PAM_National_Extension_v2.11.pdf)

**Comment by RobHolme** [comment]
This is already supported. You can define your own a schema for any custom 'Z' segments. Take a look at the "Custom Segments" section of https://github.com/RobHolme/vscode-hl7tools/blob/master/README.md#field-descriptions for instructions.

Make sure your custom segment JSON file matches the same format used for the standard segment definitions. Use the following as an example of the format required: https://github.com/RobHolme/vscode-hl7tools/blob/master/schema/2.6/segments.json 

The file needs to be a valid JSON file - any issues and an error will be raised when the file is imported. If you need to test changes to the custom schema JSON file, run the "HL7 Tools: Identify Fields" command to trigger a reload of the file.

**Comment by FFManiac** [comment]
Hi,

thank you it’s ok now.
