### ISSUE TITLE
'hl7tools.DisplaySegmentFields' failed when value present in "undefined" field

### ISSUE THREAD

**Issue by pbz** [RobHolme/vscode-hl7tools#5]
Receive the following error:

> Running the contributed command:'hl7tools.DisplaySegmentFields' failed.

The necessary conditions to reproduce seem to be having some value, in this case "N" in a field that is "undefined", in this case PID > 30 or so. If a field of PID > 30 is empty, the command runs fine but displays the field as undefined. When there is "N" or a " " in one of these fields, error. 

I went through the steps you described for a similar error, and there were no errors output in the debugger. I have modified a copy of your test message as described above, and attached for you to reproduce:

[test-undefined-with-value-error.hl7.zip](https://github.com/RobHolme/vscode-hl7tools/files/1395828/test-undefined-with-value-error.hl7.zip)

**Comment by RobHolme** [comment]
Thanks for the details and sample file, made it easy to track down the issue. I've just published an updated version (v1.6.6) that should fix the issue. Let me know if you continue to have the issue.

**Comment by pbz** [comment]
Glad the sample, etc. were helpful. Just tested out your new version and it
does indeed fix the issue as far as I can see.

Thanks for the quick fix and the awesome extension.
