### ISSUE TITLE
command 'hl7tools.DisplaySegmentFields' not found

### ISSUE THREAD

**Issue by edimaster** [RobHolme/vscode-hl7tools#8]
When I run any of the HL7Tools functions from within Visual Studio Code, I get this error.

**Comment by RobHolme** [comment]
Hi,

I've tested the attached HL7 file and haven't been able to reproduce the issue so far (tested on Windows 7, 10 and Linux). Could you try the following steps to help narrow down the cause:

1) Download a copy of the extension from https://github.com/RobHolme/vscode-hl7tools/archive/master.zip . Extract this zip file to a folder on your desktop (or other temporary location).

2) Open this folder in Visual Studio Code.

3) From the 'Debug' menu, select 'Start Debugging'. This will launch the extension in a second Visual Studio Code window, Reproduce the steps show the error message, then close the window launched by the debug command. The original Visual Studio Code window should be displaying logging information in the 'Debug Console' window. Copy the contents of the debug console to this issue thread.

**Comment by edimaster** [comment]
Rob, thank you for the quick response! I think bouncing the machine resolved the issue, no issues so far.

Thank you!
Nicholas
